source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftCompressor_Example', :exclusive => true do
  pod 'SwiftCompressor', :path => '../'
end

target 'SwiftCompressor_Tests', :exclusive => true do
  pod 'SwiftCompressor', :path => '../'

  
end
