osx_image: xcode8
language: objective-c
before_install:
  - gem install cocoapods --pre
script:
  - set -o pipefail && xcodebuild test -workspace Example/SwiftCompressor.xcworkspace -scheme SwiftCompressor-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
